### PR TITLE
Update features

### PR DESCRIPTION
**Pull request by d4n1**
Update feature (web-api-gap) in json files.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
This commit seems to introduce your local .DS_Store file

**Comment by marcoscaceres** [comment]
Ah, never mind... it's just changing mode of it?

**Comment by leandroal** [comment]
Hi Daniel,
   Please, make group your commits by features, it is better to make
references and future comments. Thanks...


[]s,
Leandro.

--
DSc. Leandro Melo de Sales
Institute of Computing (IC) at Federal University of Alagoas (UFAL), Brazil
CEO at Pervasive and Mobile Computing Laboratory (COMPELab.org / IC)
Principal at BlackBerry Tech Center LATAM
<http://www.facebook.com/leandrosalesal>
<http://www.twitter.com/leandrosalesal>
<http://www.foursquare.com/leandrosalesal>
<http://www.linkedin.com/in/leandrosalesal>

"The warrior is strong in loyalty, intensity, determination, initiative,
persistence, courage and willpower. The warrior is light in the soul,
self-trust and compassion. The warrior is often called to take the front
when other cowardly make a step backwards. There are warriors on the
battlefields and in everyday life."

2015-05-22 19:14 GMT-03:00 Marcos Caceres <notifications@github.com>:

**Comment by d4n1** [comment]
What do you suggest?

**Pull request closed without merging**
